### ISSUE TITLE
case sensitivity problem for OptCFBackup.rb

### ISSUE THREAD

**Issue by spnkr** [jmstacey/cfbackup#9]
running on os x there is no problem, but when i tried to run on ubuntu i got an error
/usr/local/lib/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require': no such file to load -- optcfbackup (LoadError)

until i did
cd /usr/lib/ruby/gems/1.8/gems/jmstacey-cfbackup-0.7.0/lib
mv OptCFBackup.rb optcfbackup.rb

i'm guessing that this is because my ubuntu box is case sensitive, but os x is not.

**Comment by jmstacey** [comment]
Thanks for the report spnkr. This should be fixed in 0.6.1 2009-05-19.

**Comment by jmstacey** [comment]
For some reason the last gem was marked as 0.7.0 but it was really 0.6.0. As such, I'm going to bump the version to 0.7.1 so that gem catches the update and I can properly handle the case issue since Git ignores the case as well and didn't update the GitHub repository.
